#!/usr/bin/env python3
"""Build a markdown table mapping each stage/module to the commit that
generated its outputs in a benchmark's `out/` tree.

Sources (inside the benchmark repo passed as an argument):
  - benchmark_conda.yaml  (which stages have which modules, pinned ref)
  - out/.modules/<repo>/<commit>/  (what was actually checked out and run)

Pinned ref resolution:
  - SHA prefix: match the directory whose name starts with that prefix.
  - branch/tag: fall back to the most recently modified commit directory
    for that repo (= what the last run used).

Usage:  build-modules-table.py <benchmark-repo> [--out PATH] [--samples-dir DIR]

When --samples-dir is given, also writes <samples-dir>/INDEX.md with one row
per collected sample, including the module id, repo link, and commit link.
Provenance is read from each <samples-dir>/<stage>/PROVENANCE.txt file written
by collect-samples.sh.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

SHA_RE = re.compile(r"^[0-9a-f]{4,40}$")


def repo_short_name(url: str) -> str:
    """Last URL segment, stripped of .git."""
    return url.rstrip("/").rsplit("/", 1)[-1].removesuffix(".git")


def resolve_commit(modules_dir: Path, repo_name: str, pinned_ref: str) -> tuple[str, str]:
    """Return (actual_commit, resolution_note).

    resolution_note explains how we got there (matched / newest / missing).
    """
    repo_dir = modules_dir / repo_name
    if not repo_dir.is_dir():
        return ("—", "not in out/.modules")

    candidates = sorted(
        (p for p in repo_dir.iterdir() if p.is_dir()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        return ("—", "empty in out/.modules")

    if SHA_RE.match(pinned_ref):
        for c in candidates:
            if c.name.startswith(pinned_ref) or pinned_ref.startswith(c.name):
                return (c.name, "matched pin")
        return (candidates[0].name, f"pin {pinned_ref} not found, using newest")

    return (candidates[0].name, f"branch '{pinned_ref}' → newest")


def collect_rows(benchmark: dict, modules_dir: Path) -> list[dict]:
    rows = []
    for stage in benchmark.get("stages", []):
        stage_id = stage.get("id", "?")
        for module in stage.get("modules", []) or []:
            repo = module.get("repository", {})
            url = repo.get("url", "")
            pin = str(repo.get("commit", ""))
            name = repo_short_name(url)
            actual, note = resolve_commit(modules_dir, name, pin)
            rows.append(
                {
                    "stage": stage_id,
                    "module": module.get("id", "?"),
                    "repo": name,
                    "url": url,
                    "pinned": pin,
                    "actual": actual,
                    "note": note,
                    "entrypoint": repo.get("entrypoint", ""),
                }
            )
    return rows


def render_markdown(rows: list[dict]) -> str:
    lines = [
        "# Module commits used in the current `out/` tree",
        "",
        "Auto-generated by `scripts/build-modules-table.py`. Do not edit by hand.",
        "",
        "| Stage | Module | Entrypoint | Pinned ref | Actual commit | Repo |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        actual_link = (
            f"[`{r['actual']}`]({r['url']}/commit/{r['actual']})"
            if r["actual"] != "—" and r["url"]
            else f"`{r['actual']}`"
        )
        note = f" <sub>{r['note']}</sub>" if r["note"] != "matched pin" else ""
        lines.append(
            f"| `{r['stage']}` | `{r['module']}` | `{r['entrypoint']}` "
            f"| `{r['pinned']}` | {actual_link}{note} "
            f"| [{r['repo']}]({r['url']}) |"
        )
    lines.append("")
    return "\n".join(lines)


def parse_provenance(provenance: Path, stage_id: str) -> list[tuple[str, str, str]]:
    """Parse a samples/<stage>/PROVENANCE.txt file.

    Returns list of (sample_file, module_id, source_path). module_id is
    derived from the omnibenchmark output path: the segment following the
    stage-id segment.
    """
    entries: list[tuple[str, str, str]] = []
    if not provenance.is_file():
        return entries
    for raw in provenance.read_text().splitlines():
        if "<-" not in raw:
            continue
        _, _, src = raw.partition("<-")
        src = src.strip()
        if not src:
            continue
        parts = Path(src).parts
        module_id = "?"
        if stage_id in parts:
            idx = parts.index(stage_id)
            if idx + 1 < len(parts):
                module_id = parts[idx + 1]
        entries.append((Path(src).name, module_id, src))
    return entries


def render_samples_index(
    rows: list[dict], samples_dir: Path, stage_order: list[str]
) -> str:
    by_stage_module: dict[tuple[str, str], dict] = {
        (r["stage"], r["module"]): r for r in rows
    }

    lines = [
        "# Samples index",
        "",
        "Auto-generated by `scripts/build-modules-table.py`. Do not edit by hand.",
        "",
        "Each row is one sample file, the module that produced it, and the",
        "git commit of that module in the most recent benchmark run.",
        "",
        "| Stage | Sample | Module | Repo | Commit |",
        "|---|---|---|---|---|",
    ]

    for stage_id in stage_order:
        stage_dir = samples_dir / stage_id
        if not stage_dir.is_dir():
            continue
        entries = parse_provenance(stage_dir / "PROVENANCE.txt", stage_id)
        if not entries:
            lines.append(
                f"| `{stage_id}` | _(no PROVENANCE.txt — rerun collect-samples.sh)_ | | | |"
            )
            continue
        for sample_name, module_id, _src in entries:
            row = by_stage_module.get((stage_id, module_id))
            sample_link = f"[`{sample_name}`](./{stage_id}/{sample_name})"
            if row is None:
                lines.append(
                    f"| `{stage_id}` | {sample_link} | `{module_id}` | — | — |"
                )
                continue
            url = row["url"]
            actual = row["actual"]
            repo_cell = f"[{row['repo']}]({url})" if url else row["repo"]
            commit_cell = (
                f"[`{actual}`]({url}/commit/{actual})"
                if actual != "—" and url
                else f"`{actual}`"
            )
            lines.append(
                f"| `{stage_id}` | {sample_link} | `{module_id}` "
                f"| {repo_cell} | {commit_cell} |"
            )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "benchmark_repo",
        type=Path,
        help="Path to the benchmark repo (must contain benchmark_conda.yaml and out/)",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output markdown path. Default: <benchmark_repo>/MODULES.md. Use '-' for stdout.",
    )
    ap.add_argument(
        "--samples-dir",
        type=Path,
        default=None,
        help="If given, also write <samples-dir>/INDEX.md with per-sample provenance.",
    )
    args = ap.parse_args()

    bench_yaml = args.benchmark_repo / "benchmark_conda.yaml"
    modules_dir = args.benchmark_repo / "out" / ".modules"

    if not bench_yaml.is_file():
        print(f"error: {bench_yaml} not found", file=sys.stderr)
        return 1
    if not modules_dir.is_dir():
        print(f"warning: {modules_dir} not found — run the benchmark first", file=sys.stderr)

    benchmark = yaml.safe_load(bench_yaml.read_text())
    rows = collect_rows(benchmark, modules_dir)
    md = render_markdown(rows)

    if str(args.out) == "-":
        sys.stdout.write(md)
    else:
        out_path = args.out or (args.benchmark_repo / "MODULES.md")
        out_path.write_text(md)
        print(f"wrote {out_path} ({len(rows)} module rows)")

    if args.samples_dir is not None:
        stage_order = [s.get("id", "?") for s in benchmark.get("stages", [])]
        idx = render_samples_index(rows, args.samples_dir, stage_order)
        idx_path = args.samples_dir / "INDEX.md"
        idx_path.write_text(idx)
        print(f"wrote {idx_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
